# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crazy_ivan}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Edward Ocampo-Gooding"]
  s.date = %q{2009-11-29}
  s.default_executable = %q{crazy_ivan}
  s.description = %q{Continuous integration should really just be a script that captures the output of running your project update & test commands and presents recent results in a static html page.

    By keeping test reports in json, per-project CI configuration in 3 probably-one-line scripts, things are kept simple, quick, and super extensible.

    Want to use git, svn, or hg? No problem.
    Need to fire off results to Twitter or Campfire? It's one line away.

    CI depends on cron.}
  s.email = %q{edward@edwardog.net}
  s.executables = ["crazy_ivan"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/crazy_ivan",
     "crazy_ivan.gemspec",
     "lib/crazy_ivan.rb",
     "lib/crazy_ivan/html_asset_crush.rb",
     "lib/crazy_ivan/report_assembler.rb",
     "lib/crazy_ivan/test_runner.rb",
     "templates/css/ci.css",
     "templates/index.html",
     "templates/javascript/builder.js",
     "templates/javascript/controls.js",
     "templates/javascript/date.js",
     "templates/javascript/dragdrop.js",
     "templates/javascript/effects.js",
     "templates/javascript/json-template.js",
     "templates/javascript/prototype.js",
     "templates/javascript/scriptaculous.js",
     "templates/javascript/slider.js",
     "test/crazy_ivan_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/edward/crazy_ivan}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Crazy Ivan (CI) is simplest possible continuous integration tool.}
  s.test_files = [
    "test/crazy_ivan_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

